language: node_js
node_js:
  - '4.1'
env:
  - DISPLAY=:99.0
before_script:
  - sh -e /etc/init.d/xvfb start
deploy:
  provider: npm
  email: christoph.burgmer@gmail.com
  api_key:
    secure: DwvZPTBukGefW2nKdm2nk8I8Pt8MxfgwxVIRLw0E0h1AwpSO//H68MNikAEh2Tt/WH3jxB49K5V2eKxF5uU5rszZwY7Gy2VjJSbErNKoirUSA5/aAuFcIJSiFNthLT1adwLWEOrSL/kdoJ1mRj4flZtYUfnGpYgqCkx+2rA8qjs=
  on:
    tags: true
    repo: cburgmer/csscritic
    all_branches: true
